config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "posts#index"

  resources :posts do
    resource :like, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: [] do
  resource :follow, only: [:create, :destroy]
end
get "users/search", to: "users#search"

resources :conversations, only: [:index, :show, :create] do
  resources :messages, only: :create
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :content, presence: true
end

app/models/conversation.rb
# app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :user1, class_name: "User"
  belongs_to :user2, class_name: "User"

  has_many :messages, dependent: :destroy

 def self.between(user_a, user_b)
    where(
      "(user1_id = ? AND user2_id = ?) OR (user1_id = ? AND user2_id = ?)",
      user_a.id, user_b.id,
      user_b.id, user_a.id
    ).first
  end

  def other_user(current_user)
    current_user == user1 ? user2 : user1
  end
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  validates :follower_id, uniqueness: { scope: :following_id }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
   validates :user_id, uniqueness: { scope: :post_id }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation
  validates :content, presence: true
  after_create_commit do
  broadcast_append_to(
    "conversation_#{conversation_id}",
    target: "messages",
    partial: "messages/message",
    locals: { message: self, current_user_id: user_id }
  )
end 
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :actor
  belongs_to :notifiable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
   has_many_attached :media
  has_many :likes, dependent: :destroy
def liked_by?(user)
  likes.exists?(user: user)
end
has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

 def like(post)
  likes.find_or_create_by(post: post)
end

def unlike(post)
  likes.where(post: post).destroy_all
end

def liked?(post)
  likes.exists?(post: post)
end

  has_many :comments
  has_one_attached :avatar
  validates :username, presence: true, uniqueness: true

  has_many :active_follows,
  class_name: "Follow",
  foreign_key: :follower_id,
  dependent: :destroy

  has_many :passive_follows,
  class_name: "Follow",
  foreign_key: :following_id,
  dependent: :destroy

  has_many :following, through: :active_follows, source: :following
  has_many :followers, through: :passive_follows, source: :follower

  def following?(user)
    following.include?(user)
  end

  def friends_with?(user)
    following?(user) && user.following?(self)
  end

  has_many :sent_messages, class_name: "Message"

has_many :conversations_as_user1,
  class_name: "Conversation",
  foreign_key: :user1_id

has_many :conversations_as_user2,
  class_name: "Conversation",
  foreign_key: :user2_id

def conversations
  Conversation.where("user1_id = ? OR user2_id = ?", id, id)
end
def friends
  following & followers
end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(
      user: current_user,
      content: params[:comment][:content]
    )

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to posts_path }
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to posts_path }
    end
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!

def create
  @user = User.find(params[:user_id])
  current_user.active_follows.create(following: @user)
end

def destroy
  @user = User.find(params[:user_id])
  follow = current_user.active_follows.find_by(following: @user)
  follow&.destroy
end
end

app/controllers/likes_controller.rb
  class LikesController < ApplicationController
    before_action :authenticate_user!


  def create
    @post = Post.find(params[:post_id])
    @post.likes.create(user: current_user)

    respond_to do |format|
      format.turbo_stream
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @post.likes.find_by(user: current_user)&.destroy

    respond_to do |format|
      format.turbo_stream
    end
  end





  end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @conversation = Conversation.find(params[:conversation_id])
    @message = @conversation.messages.create(
      user: current_user,
      content: params[:message][:content]
    )
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

 def index
   @conversations = current_user.conversations if user_signed_in?
  if params[:query].present?
    q = params[:query].downcase

    @posts = Post
      .joins(:user)
      .where(
        "LOWER(users.username) LIKE :q OR LOWER(posts.caption) LIKE :q",
        q: "%#{q}%"
      )
      .distinct
      .order(created_at: :desc)
  else
    @posts = Post.order(created_at: :desc)
  end
end


  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  private

  def post_params
  params.require(:post).permit(:caption, media: [])
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def search
    if params[:query].present?
     query = params[:query].downcase

@users = User
  .where("LOWER(username) LIKE ?", "%#{query}%")
  .where.not(id: current_user.id)

    else
      @users = []
    end

    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(user, css_class: "")
    if user&.avatar&.attached?
      image_tag user.avatar, class: css_class
    else
      image_tag "default_avatar.png", class: css_class
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div id="comment_<%= comment.id %>" class="comment">

  <div class="comment-avatar">
     <% if comment.user.avatar.attached? %>
          <%= image_tag comment.user.avatar, class: "avatar" %>
        <% else %>
          <%= image_tag "default_avatar.png", class: "avatar" %>
        <% end %>
  </div>

  <div class="comment-body">
    <span class="comment-username"><%= comment.user.username %></span><span class="comment-content"><%= comment.content %></span>
  </div>

  <% if comment.user == current_user %>
    <%= button_to post_comment_path(comment.post, comment),
      method: :delete,
      form: { data: { turbo_stream: true } },
      class: "comment-delete" do %>
      🗑️
    <% end %>
  <% end %>

</div>


app/views/comments/_form.html.erb
<%= form_with model: [post, Comment.new],
      id: "comment_form_#{post.id}" do |f| %>

  <%= f.text_field :content,
        placeholder: "Añade un comentario...",
        class: "comment-input" %>

  <%= f.submit "Publicar", class: "comment-submit" %>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.append "comments_#{@post.id}",
      partial: "comments/comment",
      locals: { comment: @comment } %>

<%= turbo_stream.replace "comment_form_#{@post.id}",
      partial: "comments/form",
      locals: { post: @post } %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove "comment_#{@comment.id}" %>

app/views/follows/create.turbo_stream.erb
<%= turbo_stream.replace dom_id(@user, :follow) do %>
  <%= render "users/follow_button", user: @user %>
<% end %>


app/views/follows/destroy.turbo_stream.erb
<%= turbo_stream.replace dom_id(@user, :follow) do %>
  <%= render "users/follow_button", user: @user %>
<% end %>

app/views/likes/_button.html.erb
<% liked = post.likes.exists?(user: current_user) %>

<div class="like-wrapper">
  <%= button_to post_like_path(post),
    method: liked ? :delete : :post,
    data: { turbo: true },
    class: "like-btn" do %>
    <%= liked ? "❤️" : "🤍" %>
  <% end %>

  <span class="like-count">
    <%= post.likes.count %>
  </span>
</div>



app/views/likes/create.turbo_stream.erb
<%= turbo_stream.replace "post_#{@post.id}_like" do %>
  <div id="post_<%= @post.id %>_like">
    <%= render "likes/button", post: @post %>
  </div>
<% end %>



app/views/likes/destroy.turbo_stream.erb
<%= turbo_stream.replace "post_#{@post.id}_like" do %>
  <div id="post_<%= @post.id %>_like">
    <%= render "likes/button", post: @post %>
  </div>
<% end %>




app/views/messages/_message.html.erb
<div class="message <%= "me" if message.user_id == current_user_id %>">
  <%= message.content %>
</div>

app/views/messages/create.turbo_stream.erb
<%= turbo_stream.append "messages",
  partial: "messages/message",
  locals: {
    message: @message,
    current_user_id: current_user.id
  } %>


app/views/posts/index.html.erb
<main>
<div class="feed">
  <% if @posts.empty? %>
  <% if params[:query].present? %>
    <div class="no-results">
      No hay resultados para "<strong><%= params[:query] %></strong>"
    </div>
  <% else %>
    <div class="no-results">
      Aún no hay publicaciones
    </div>
  <% end %>
<% end %>

  <% @posts.each do |post| %>
    <div class="post-card">
      <div class="post-header">
        <div class="post-user">
   <% if post.user.avatar.attached? %>
          <%= image_tag post.user.avatar, class: "avatar" %>
        <% else %>
          <%= image_tag "default_avatar.png", class: "avatar" %>
        <% end %>

  <strong>@<%= post.user.username %></strong>
</div>

      </div>
      
<% if post.media.attached? %>
  <div class="carousel" data-carousel>

    <% if post.media.count > 1 %>
      <button class="carousel-btn prev" type="button">‹</button>
    <% end %>

    <div class="carousel-track">
      <% post.media.each do |file| %>
        <div class="carousel-item">

          <div class="post-media-frame">
            <% if file.image? %>
              <%= image_tag file, class: "post-media" %>

         <% elsif file.video? %>
  <div class="video-wrapper post-media">
    <video
      class="post-media post-video"
      muted
      loop
      playsinline
      preload="metadata"
      data-video
    >
      <source src="<%= url_for(file) %>" type="<%= file.content_type %>">
    </video>

    <button class="mute-btn" type="button">🔇</button>
  </div>
<% end %>
          </div>

        </div>
      <% end %>
    </div>

    <% if post.media.count > 1 %>
      <button class="carousel-btn next" type="button">›</button>
    <% end %>

    <% if post.media.count > 1 %>
      <div class="carousel-dots">
        <% post.media.each_with_index do |_, index| %>
          <span
            class="dot <%= 'active' if index == 0 %>"
            data-index="<%= index %>">
          </span>
        <% end %>
      </div>
    <% end %>

  </div>
<% end %>






<div class="like-section">
<div id="post_<%= post.id %>_like">
  <%= render "likes/button", post: post %>
</div>







 
</div>

<% if post.caption.present? %>
  <div class="post-body">
    <div class="post-user-caption">
      
      <div class="avatar-container">
        <% if post.user.avatar.attached? %>
          <%= image_tag post.user.avatar, class: "avatar" %>
        <% else %>
          <%= image_tag "default_avatar.png", class: "avatar" %>
        <% end %>
      </div>

      <div class="post-caption-content">
        <strong class="username-text">@<%= post.user.username %></strong><span class="caption-text"><%= post.caption %></span>
      </div>

    </div>
  </div>
<% end %>

<div class="comments-section">
  <button class="toggle-comments-btn">
    Ver comentarios
  </button>
  <div class="comments-box hidden">
    <div id="comments_<%= post.id %>" class="comments">
  <%= render post.comments %>
</div>

   <div class="comment-form">
  <%= render "comments/form", post: post %>
</div>

  </div>

</div>



    </div>
  <% end %>


</div>

<button id="toggle-sidebar" class="messages-btn">
  💬 Mensajes
</button>


</div>
</main>

<script>
 // Definimos la función fuera para que sea una referencia estable
// 1. Forzar Modo Oscuro Siempre (Incluso antes de que cargue el body)


// 2. Función de Toggle
const globalSidebarToggle = (e) => {
    const btn = e.target.closest("#toggle-sidebar");
    if (btn) {
        const sidebar = document.getElementById("sidebar");
        if (sidebar) {
            sidebar.classList.toggle("active");
        }
    }
};

// 3. Vincular al objeto WINDOW (Máxima jerarquía)
// Esto sobrevive a cambios de HTML, Turbo y navegación hacia atrás
if (!window.sidebarInitialized) {
    window.addEventListener("click", globalSidebarToggle);
    window.sidebarInitialized = true;
}


</script>

app/views/posts/new.html.erb
<%= form_with model: @post, local: true, html: { multipart: true }, class: "new-post-form" do |f| %>

  <div class="post-image-upload">
    <%= f.label :media, class: "image-label" do %>
      <span>📷 Seleccionar contenido</span>
    <% end %>

    <%= f.file_field :media,
          multiple: true,
          accept: "image/*,video/*",
          class: "image-input" %>
  </div>

  <div class="post-caption">
    <%= f.text_area :caption,
      placeholder: "Escribe una descripción...",
      rows: 3 %>
  </div>

  <%= f.submit "Publicar", class: "post-submit" %>

<% end %>




app/views/users/_follow_button.html.erb

<% if current_user.friends_with?(user) %>
  <span class="friend-status">Amigos</span>

<% elsif current_user.following?(user) %>
  <%= button_to "Siguiendo",
      user_follow_path(user),
      method: :delete,
      form: { class: "follow-form" },
      class: "btn-custom following" %>

<% elsif user.following?(current_user) %>
  <%= button_to "Seguir también",
      user_follow_path(user),
      method: :post,
      form: { class: "follow-form" },
      class: "btn-custom follow-back" %>

<% else %>
  <%= button_to "Seguir",
      user_follow_path(user),
      method: :post,
      form: { class: "follow-form" },
      class: "btn-custom primary" %>
<% end %>

app/views/users/search.html.erb
<turbo-frame id="user_search_results">
  <% if params[:query].blank? %>
    <!-- nada -->
  <% elsif @users.empty? %>
    <p class="sidebar-empty">Usuario inexistente</p>
  <% else %>
    <% @users.each do |user| %>
      <div class="user-result">
        <%= image_tag(
          user.avatar.attached? ? user.avatar : "default_avatar.png",
          class: "friend-avatar"
        ) %>

        <span class="friend-username"><%= user.username %></span>

        <div id="<%= dom_id(user, :follow) %>">
          <%= render "users/follow_button", user: user %>
        </div>
      </div>
    <% end %>
  <% end %>
</turbo-frame>


app/views/users/search.turbo_stream.erb
<%= turbo_stream.replace "user_search_results" do %>
  <% if @users.empty? %>
    <p class="sidebar-empty">Usuario inexistente</p>
  <% else %>
    <% @users.each do |user| %>
      <div class="user-result">
        <%= image_tag(
          user.avatar.attached? ? user.avatar : "default_avatar.png",
          class: "friend-avatar"
        ) %>

        <span class="friend-username"><%= user.username %></span>

        <div class="follow-btn">
          <%= render "users/follow_button", user: user %>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>