config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "posts#index"

  resources :posts do
    resource :like, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: [] do
  resource :follow, only: [:create, :destroy]
end
get "users/search", to: "users#search"

resources :conversations, only: [:index, :show, :create] do
  resources :messages, only: :create
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :content, presence: true
end

app/models/conversation.rb
# app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :user1, class_name: "User"
  belongs_to :user2, class_name: "User"

  has_many :messages, dependent: :destroy

 def self.between(user_a, user_b)
    where(
      "(user1_id = ? AND user2_id = ?) OR (user1_id = ? AND user2_id = ?)",
      user_a.id, user_b.id,
      user_b.id, user_a.id
    ).first
  end

  def other_user(current_user)
    current_user == user1 ? user2 : user1
  end
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  validates :follower_id, uniqueness: { scope: :following_id }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
   validates :user_id, uniqueness: { scope: :post_id }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation
  validates :content, presence: true
  after_create_commit do
  broadcast_append_to(
    "conversation_#{conversation_id}",
    target: "messages",
    partial: "messages/message",
    locals: { message: self, current_user_id: user_id }
  )
end 
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :actor
  belongs_to :notifiable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
   has_many_attached :media
  has_many :likes, dependent: :destroy
def liked_by?(user)
  likes.exists?(user: user)
end
has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

 def like(post)
  likes.find_or_create_by(post: post)
end

def unlike(post)
  likes.where(post: post).destroy_all
end

def liked?(post)
  likes.exists?(post: post)
end

  has_many :comments
  has_one_attached :avatar
  validates :username, presence: true, uniqueness: true

  has_many :active_follows,
  class_name: "Follow",
  foreign_key: :follower_id,
  dependent: :destroy

  has_many :passive_follows,
  class_name: "Follow",
  foreign_key: :following_id,
  dependent: :destroy

  has_many :following, through: :active_follows, source: :following
  has_many :followers, through: :passive_follows, source: :follower

  def following?(user)
    following.include?(user)
  end

  def friends_with?(user)
    following?(user) && user.following?(self)
  end

  has_many :sent_messages, class_name: "Message"

has_many :conversations_as_user1,
  class_name: "Conversation",
  foreign_key: :user1_id

has_many :conversations_as_user2,
  class_name: "Conversation",
  foreign_key: :user2_id

def conversations
  Conversation.where("user1_id = ? OR user2_id = ?", id, id)
end
def friends
  following & followers
end

end

app/controllers/likes_controller.rb
  class LikesController < ApplicationController
    before_action :authenticate_user!


  def create
    @post = Post.find(params[:post_id])
    @post.likes.create(user: current_user)

    respond_to do |format|
      format.turbo_stream
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @post.likes.find_by(user: current_user)&.destroy

    respond_to do |format|
      format.turbo_stream
    end
  end





  end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

 def index
   @conversations = current_user.conversations if user_signed_in?
  if params[:query].present?
    q = params[:query].downcase

    @posts = Post
      .joins(:user)
      .where(
        "LOWER(users.username) LIKE :q OR LOWER(posts.caption) LIKE :q",
        q: "%#{q}%"
      )
      .distinct
      .order(created_at: :desc)
  else
    @posts = Post.order(created_at: :desc)
  end
end


  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  private

  def post_params
  params.require(:post).permit(:caption, media: [])
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def search
    if params[:query].present?
     query = params[:query].downcase

@users = User
  .where("LOWER(username) LIKE ?", "%#{query}%")
  .where.not(id: current_user.id)

    else
      @users = []
    end

    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(user, css_class: "")
    if user&.avatar&.attached?
      image_tag user.avatar, class: css_class
    else
      image_tag "default_avatar.png", class: css_class
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instogram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag 'favicon.png' %>

  </head>
  <% if user_signed_in? %>
  <body>
  <nav class="navbar">
  <div class="nav-left">
    <%= link_to "Instogram", root_path, class: "logo" %>
  </div>
   <div class="navbar-search">
  <%= form_with url: posts_path, method: :get, local: true do |f| %>
    <%= f.text_field :query,
      placeholder: "🔍 Buscar",
      class: "search-input",
      value: params[:query] %>
  <% end %>
</div>

  <div class="nav-right">
    

      <%= link_to "Nuevo", new_post_path, class: "nav-link" %>

    


      <%= button_to "Salir",
          destroy_user_session_path,
          method: :delete,
          class: "nav-link logout",
          form: { class: "logout-form" } %>

      <%= link_to edit_user_registration_path, class: "profile-link" do %>
        <% if current_user.avatar.attached? %>
          <%= image_tag current_user.avatar, class: "nav-avatar" %>
        <% else %>
          <%= image_tag "default_avatar.png", class:"nav-avatar placeholder" %>

        <% end %>

        <span class="nav-username">
          <%= current_user.username %>
        </span>
      <% end %>

    <% end %>
  </div>
</nav>

<div class="layout">
  <% if user_signed_in? %>
    <%= render "shared/sidebar" %>
  <% end %>

  <main class="container feed">
    <%= yield %>
  </main>
</div>


  </body>
</html>

app/views/shared/_sidebar.html.erb
<% return unless user_signed_in? %>
<div class="messaging-layout">
<aside id="sidebar" class="sidebar">

  <div class="sidebar-section">
    <div class="sidebar-section">
  <h4>Buscar usuarios</h4>
<div class="user-search-wrapper">
  <%= form_with url: users_search_path,
      method: :get,
      data: { turbo_frame: "user_search_results" },
      class: "user-search-form" do |f| %>

    <%= f.text_field :query,
        placeholder: "Buscar usuario",
        class: "user-search-input" %>
  <% end %>

  <turbo-frame id="user_search_results">
    <p class="sidebar-empty">Busca usuarios</p>
  </turbo-frame>
</div>
</div>


<h4>Mensajes</h4>

<% if current_user.friends.empty? %>
  <p class="sidebar-empty">
    No tienes amigos a quienes enviar mensaje
  </p>
<% else %>
  <% current_user.friends.each do |friend| %>
    <%= button_to conversations_path(user_id: friend.id),
        method: :post,
        class: "message-user-btn" do %>

      <div class="message-user">
        <% if friend.avatar.attached? %>
          <%= image_tag friend.avatar, class: "sidebar-avatar" %>
        <% else %>
          <%= image_tag "default_avatar.png", class: "sidebar-avatar" %>
        <% end %>

        <span><%= friend.username %></span>
      </div>

    <% end %>
  <% end %>
<% end %>


</aside>
</div>